/* ========================================================================
 * Copyright 2014 pareja13
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 pareja13

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/
define(['controller/_profesorController','delegate/profesorDelegate'], function() {
    App.Controller.ProfesorController = App.Controller._ProfesorController.extend({
        postInit: function(options){
            var self = this;
            this.listProfesoresDestacadosTemplate = _.template($('#profesoresDestacadosList').html());
            this.listProfesoresDestacadosModelClass = options.listModelClass;
        },
        _renderPromedio: function() {
            var self = this;
            /*Aquí se utiliza el efecto gráfico backbone deslizar. “$el” hace referencia al <div id=”main”> ubicado en el index.html. Dentro de este div se despliegue la tabla.*/
            this.$el.slideUp("fast", function() {
                /*Establece que en el <div> se despliegue el template de la variable “”. Como parámetros entran las variables establecidas dentro de los tags <%%> con sus valores como un objeto JSON. En este caso, la propiedad sports tendrá la lista que instanció “sportSearch” en la variable del bucle <% _.each(sports, function(sport) { %>*/
 
                self.$el.html(self.listProfesoresDestacadosTemplate({profesores: self.profesoresDestacadosModelList.models}));
                self.$el.slideDown("fast");
            });
        },
        profesoresDestacados: function(params) {
        //Elementos para invocar el servicio getSports
            if (params) {
                var data = params.data;
            }
            if (App.Utils.eventExists(this.componentId + '-' + 'instead-profesor-list')) {
                Backbone.trigger(this.componentId + '-' + 'instead-profesor-list', {view: this, data: data});
            } else {
                Backbone.trigger(this.componentId + '-' + 'pre-profesor-list', {view: this, data: data});
                var self = this;
                if (!this.profesorModelList) {
                    this.profesorModelList = new this.listModelClass();
                }
                //se obtienen los deportes del servicio getSports
                this.profesorModelList.fetch({
                    data: data,
                    success: function() {
                        var elementos = self.profesorModelList.models;
                        //Ahora se instancia el nuevo modelo construido
                        self.profesoresDestacadosModelList = new App.Model.ProfesoresDestacadosList;
                        //Se itera sobre la variable elementos, que corresponden a la lista de modelos obtenida del servico REST getSports
                        _.each(elementos, function(d) {
                            //Se hace el cálculo del nuevo campo
                            var x = d.attributes.fechaVinculacion;
                            var y = d.split(",");
                            var z = parseInt(y[2]);
                            var actual = new Date();
                            var date = actual.getFullYear();
                            var vinc = "" + (date-z);
                            /*Ahora se instancia un SportPromModel, con un nuevo objeto JSON como parámetro como constructor (antes sportModel), extrayendo los datos de “d”.*/
                            var model = new App.Model.ProfesoresDestacadosModel({name: d.attributes.name, vinculacion: vinc});
                            //y se agrega finalmente a los modelos prom de la lista.
                            self.profesoresDestacadosModelList.models.push(model);
                        });
                        //Se invoca la función de renderizado para que muestre los resultados en la nueva lista.
                        self._renderPromedio(params);
                        Backbone.trigger(self.componentId + '-' + 'post-profesor-list', {view: self});
                    },
                    error: function(mode, error) {
                        Backbone.trigger(self.componentId + '-' + 'error', {event: 'profesor-list', view: self, error: error});
                    }
                });
            }
        }

    });
    return App.Controller.ProfesorController;
}); 